### ISSUE TITLE
Create Folder

### ISSUE THREAD

**Issue by CrackerakiUA** [niftylettuce/node-google-drive#25]
I don't see in the API route for that, is that possible with our module?

**Comment by doug-wade** [comment]
It is!  A folder is just a special kind of file with the [MIME type `application/vnd.google-apps.folder`](https://developers.google.com/drive/v2/web/folder), so `touch`ing or `insert`ing a file with that MIME type and the proper parent will create the proper folder or subfolder.

**Comment by CrackerakiUA** [comment]
Cool, yes logically. Thank you.
