### ISSUE TITLE
Description

### ISSUE THREAD

**Issue by krishan1kamal** [niftylettuce/node-google-drive#26]
Any body Please explain what i will pass in params and meta i am new with google drive 

Thanks
krishan

**Comment by doug-wade** [comment]
Hi @krishan1kamal!  The params are different per method.  For instance, for the call

```
// Files - Insert
googleDrive(token).files().insert(meta, params, callback)
```

You can find the parameters that you can put into the param hash are those listed under the "Parameters" header from https://developers.google.com/drive/v2/reference/files/insert

**Comment by krishan1kamal** [comment]
Thanks @doug-wade
